// Auto-generated by deploy.cjs — DO NOT EDIT MANUALLY
// Network: monad-testnet
// Deployed: 2026-02-28T07:16:18.030Z

export const CONTRACT_ADDRESSES = {
  GAME_CONTRACT:        "0x1084c097e211E488041BC38CF926C82584890DA5",
  LEADERBOARD_CONTRACT: "0x75B6D31d2c48bBCf42037c79708640916DE73bFc",
  NFT_CONTRACT:         "0xA6EF03b53Bb8ae3914AAED537c6e6C1c3F8c0117",
  LOBBY_CONTRACT:       "0x6f0fB75296Ba117A83023648e1b57ef653560Fe7",
} as const;

export const NETWORK_CONFIG = {
  chainId:  10143,
  name:     "Monad Testnet",
  rpcUrl:   "https://testnet-rpc.monad.xyz",
  explorer: "https://testnet.monadexplorer.com",
  currency: "MON",
  faucet:   "https://faucet.monad.xyz",
} as const;
