const hre = require("hardhat");
const fs  = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  const network    = hre.network.name;

  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("  POLITICIAN SURFERS — Deploying to", network.toUpperCase());
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("Deployer :", deployer.address);

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log("Balance  :", hre.ethers.formatEther(balance), "MON");
  console.log("");

  // ── 1. Deploy PoliticianSurfers ──────────────────────────────────────────
  console.log("1/3  Deploying PoliticianSurfers...");
  const t0 = Date.now();
  const GameFactory   = await hre.ethers.getContractFactory("PoliticianSurfers");
  const gameContract  = await GameFactory.deploy();
  await gameContract.waitForDeployment();
  const gameAddr = await gameContract.getAddress();
  console.log("     ✅ PoliticianSurfers deployed:", gameAddr, `(${Date.now() - t0} ms)`);

  // ── 2. Deploy Leaderboard ────────────────────────────────────────────────
  console.log("2/3  Deploying Leaderboard...");
  const t1 = Date.now();
  const LBFactory    = await hre.ethers.getContractFactory("Leaderboard");
  const lbContract   = await LBFactory.deploy();
  await lbContract.waitForDeployment();
  const lbAddr = await lbContract.getAddress();
  console.log("     ✅ Leaderboard deployed:", lbAddr, `(${Date.now() - t1} ms)`);

  // ── 3. Deploy PoliticianNFT ──────────────────────────────────────────────
  console.log("3/3  Deploying PoliticianNFT...");
  const t2 = Date.now();
  const NFTFactory   = await hre.ethers.getContractFactory("PoliticianNFT");
  const nftContract  = await NFTFactory.deploy();
  await nftContract.waitForDeployment();
  const nftAddr = await nftContract.getAddress();
  console.log("     ✅ PoliticianNFT deployed:", nftAddr, `(${Date.now() - t2} ms)`);

  console.log("");
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("  ALL CONTRACTS DEPLOYED ✅");
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("  Game Contract  :", gameAddr);
  console.log("  Leaderboard    :", lbAddr);
  console.log("  NFT Contract   :", nftAddr);
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

  // ── Write addresses file for frontend ────────────────────────────────────
  const addressesDir  = path.join(__dirname, "../src/contracts");
  if (!fs.existsSync(addressesDir)) fs.mkdirSync(addressesDir, { recursive: true });

  const addressesContent = `// Auto-generated by deploy.js — DO NOT EDIT MANUALLY
// Network: ${network}
// Deployed: ${new Date().toISOString()}

export const CONTRACT_ADDRESSES = {
  GAME_CONTRACT:       "${gameAddr}",
  LEADERBOARD_CONTRACT:"${lbAddr}",
  NFT_CONTRACT:        "${nftAddr}",
} as const;

export const NETWORK_CONFIG = {
  chainId:     10143,
  name:        "Monad Testnet",
  rpcUrl:      "https://testnet-rpc.monad.xyz",
  explorer:    "https://testnet.monadexplorer.com",
  currency:    "MON",
  faucet:      "https://faucet.monad.xyz",
} as const;
`;
  fs.writeFileSync(path.join(addressesDir, "addresses.ts"), addressesContent);
  console.log("\n  📄 addresses.ts written to src/contracts/addresses.ts");
  console.log("  👉 Run: npm run dev");
  console.log("  👉 Open MetaMask → Monad Testnet (Chain ID 10143)");
  console.log("  👉 Faucet: https://faucet.monad.xyz\n");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
