const hre  = require("hardhat");
const fs   = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  const network    = hre.network.name;

  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("  POLITICIAN SURFERS — Deploying to", network.toUpperCase());
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("Deployer :", deployer.address);
  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log("Balance  :", hre.ethers.formatEther(balance), "MON\n");

  if (parseFloat(hre.ethers.formatEther(balance)) < 0.05) {
    console.error("❌ Insufficient MON balance! Get testnet MON from https://faucet.monad.xyz");
    process.exit(1);
  }

  // ── 1. PoliticianSurfers ─────────────────────────────────────────────────
  console.log("1/3  Deploying PoliticianSurfers...");
  const t0 = Date.now();
  const GameFactory  = await hre.ethers.getContractFactory("PoliticianSurfers");
  const gameContract = await GameFactory.deploy();
  await gameContract.waitForDeployment();
  const gameAddr = await gameContract.getAddress();
  console.log(`     ✅ PoliticianSurfers: ${gameAddr}  (${Date.now() - t0}ms)\n`);

  // ── 2. Leaderboard ───────────────────────────────────────────────────────
  console.log("2/3  Deploying Leaderboard...");
  const t1 = Date.now();
  const LBFactory  = await hre.ethers.getContractFactory("Leaderboard");
  const lbContract = await LBFactory.deploy();
  await lbContract.waitForDeployment();
  const lbAddr = await lbContract.getAddress();
  console.log(`     ✅ Leaderboard: ${lbAddr}  (${Date.now() - t1}ms)\n`);

  // ── 3. PoliticianNFT ─────────────────────────────────────────────────────
  console.log("3/3  Deploying PoliticianNFT...");
  const t2 = Date.now();
  const NFTFactory  = await hre.ethers.getContractFactory("PoliticianNFT");
  const nftContract = await NFTFactory.deploy();
  await nftContract.waitForDeployment();
  const nftAddr = await nftContract.getAddress();
  console.log(`     ✅ PoliticianNFT: ${nftAddr}  (${Date.now() - t2}ms)\n`);

  // ── Summary ──────────────────────────────────────────────────────────────
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("  ALL 3 CONTRACTS DEPLOYED ✅");
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("  Game        :", gameAddr);
  console.log("  Leaderboard :", lbAddr);
  console.log("  NFT         :", nftAddr);
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");

  // ── Write addresses.ts ───────────────────────────────────────────────────
  const addressesPath = path.join(__dirname, "../src/contracts/addresses.ts");
  fs.writeFileSync(addressesPath, `// Auto-generated by deploy.cjs — DO NOT EDIT MANUALLY
// Network: ${network}
// Deployed: ${new Date().toISOString()}

export const CONTRACT_ADDRESSES = {
  GAME_CONTRACT:        "${gameAddr}",
  LEADERBOARD_CONTRACT: "${lbAddr}",
  NFT_CONTRACT:         "${nftAddr}",
} as const;

export const NETWORK_CONFIG = {
  chainId:  10143,
  name:     "Monad Testnet",
  rpcUrl:   "https://testnet-rpc.monad.xyz",
  explorer: "https://testnet.monadexplorer.com",
  currency: "MON",
  faucet:   "https://faucet.monad.xyz",
} as const;
`);

  console.log("  📄 addresses.ts written → src/contracts/addresses.ts");
  console.log(`  🔍 Explorer: https://testnet.monadexplorer.com/address/${gameAddr}`);
  console.log("  ▶  Run: npm run dev\n");
}

main().catch((e) => { console.error(e); process.exit(1); });
